### ISSUE TITLE
ginkgo ota update verification failed

### ISSUE THREAD

**Issue by rexVictor** [crdroidandroid/issue_tracker#468]
### Issue type

Feature not working as intended

### Device

Redmi Note 8T (ginkgo)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2024-07-18

### Bug description

After I had been notified about a new update, I selected Download as usual. But after the download finished, I got an error about a verification failure and the update cannot be installed

### Steps to reproduce

1. Go to Settings
2. System
3. System Updates
4. Refresh if necessary
5. Hit "Download" on crDroid 10.6 July 18, 2024

### Relevant log (logcat/build log)

```shell
UpdaterController: Download complete
UpdaterController: Verification failed
UpdaterController: java.security.SignatureException: signature doesn't match any trusted key
UpdaterController:      at android.os.RecoverySystem.verifyPackage(RecoverySystem.java:362)
UpdaterController: 	at com.crdroid.updater.controller.UpdaterController.verifyPackage(UpdaterController.java:278)
UpdaterController: 	at com.crdroid.updater.controller.UpdaterController.lambda$verifyUpdateAsync$0(UpdaterController.java:258)
UpdaterController: 	at com.crdroid.updater.controller.UpdaterController.$[censored](UpdaterController.java:0)
UpdaterController: 	at com.crdroid.updater.controller.UpdaterController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
UpdaterController: 	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ByAndrius** [comment]
Have you already tried update the ROM in Recovery-mode?

**Comment by rexVictor** [comment]
No, I have not. If necessary, I will do it. Will I lose any data when doing it over recovery instead of ota? And is the not working ota-update intended? Will this be the default in the future?

**Comment by ByAndrius** [comment]
As far as I know, no data is lost when flashing the update via Recovery. (This is how I updated my Redmi Note 8 Pro).

Since I am not a ROM developer, I couldn't guarantee that the OTA will work in the future. What I do know is that recently there was a change in "signatures" (I think that's what it's called), and for that reason the OTA cannot update the ROM correctly.

The maintainer of our devices (I think DarkJoker) on his Telegram indicated that, for my device, it was required to update from the recovery.
![IMG_20240720_184947](https://github.com/user-attachments/assets/c5b427a2-dd14-42f6-b992-f96a56372155)

Maybe it will also be the case with your device...? Don't know. It's strange, because there is no note on your particular device.
![IMG_20240720_185004](https://github.com/user-attachments/assets/9de06e61-2553-4b7f-8ceb-03abfd7612ea)

**Comment by gwolf2u** [comment]
sideload update in recovery
boot to recovery
install crdroid.zip
reboot to recovery
install gapps.zip (if you had gapps)
reboot
