### ISSUE TITLE
bug: Charging limit seems not works properly

### ISSUE THREAD

**Issue by rgwan** [crdroidandroid/issue_tracker#588]
### Issue type

Feature not working as intended

### Device

lmi (Redmi K30 Pro Zoom Edition)

### crDroid version

crDroid 11

### Exact version / Build date

crDroid version 11.0/2024-12-19

### Bug description

It' about charging limit setting, whenI set the charging limit to 85%, when the meter shows 85%, the charging progress stopped as expected, and then the USB current drops to zero, which indicates the battery is powering the system.  Left it for an hour, the battery meter shows 80% and the charging process does not restart.

I expect the behavior of charging limit is that when it reaches the limit, the charging progress stops and the phone is powered by USB, and the battery enters idle state.

### Steps to reproduce

1. Go to crDroid settings -> battery -> charging control
2. Set charging mode to 'limited by percent' and set the upper limit slider to 85%.
3. Connect the usb cable and wait for it reaches the limit.
4. Wait for it slowly discharge.

### Relevant log (logcat/build log)

```shell
I'm sorry, I don't know how to export charging log.
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is by design
so lets say you limit charging to 80%
you should not recharge from 79% to 80% and again when reach 79% and so on
that destroys cell charging cycles
when reaches the percentage, power is cut and from there rely on battery
this implementation is more generic in order to handle all devices old or new
ofc newer devices have the capability to even use power from the plug when reaches the charging percentage, but that's something else

**Comment by ossilator** [comment]
> you should not recharge from 79% to 80% and again when reach 79% and so on
> that destroys cell charging cycles

this is completely wrong.
the shallower the DoD, the more cycles the battery can do, and disproportionately more so than total charge transferred would suggest. this is easily explained by the reduced mechanical stress from electrode expansion/contraction due to (dis-)charging.

**Comment by rgwan** [comment]
> > you should not recharge from 79% to 80% and again when reach 79% and so on
> > that destroys cell charging cycles
> 
> this is completely wrong. the shallower the DoD, the more cycles the battery can do, and disproportionately more so than total charge transferred would suggest. this is easily explained by the reduced mechanical stress from electrode expansion/contraction due to (dis-)charging.

Yes, that's right. It's a Li-Po battery, not NI-MH battery, shallower DoD will give much life to the battery, especially when the device is plugged into the main's power continuously. @gwolf2u Please consider to add new charging mode or fix that issue, Thank you!

**Comment by ossilator** [comment]
this isn't really all that different for ni-mh batteries, though the disproportionate effect may plausibly be stronger for lithium cells.

if that's what you're alluding to: the only batteries that suffer a real memory effect are a particular construction of ni-cd cells. for the others it's really about overcharge due to unmanaged trickle-charging, which was commonly done for nickel-based batteries.
